#Automatically generated by pip2arch on 2015-04-27

pkgname=python-css-html-js-minify
pkgver=1.0.13
pkgrel=1
pkgdesc="StandAlone Async single-file cross-platform no-dependencies Unicode-ready Python3-ready Minifier for the Web."
url="https://github.com/juancarlospaco/css-html-js-minify"
depends=('python' 'pip')
makedepends=('python3' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/source/c/css-html-js-minify/css-html-js-minify-1.0.13.zip')
md5sums=('3566f26423f99fb702e74ecc212fa7b3')

build() {
    cd $srcdir/css-html-js-minify-1.0.13
    python setup.py build
}

package() {
    cd $srcdir/css-html-js-minify-1.0.13
    python setup.py install --root="$pkgdir" --optimize=1 
}
